services:
  ros2_jammy_sim:
    build:
      context: ./docker_simulator/DockerFiles
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=osrf/ros
        - BASE_TAG=jazzy-desktop-full
        - DISTRO=jazzy
        - IMAGE_NAME=docker_control_simulation
        - IMAGE_TAG=0.1
        - WORKSPACE=docker_simulation_ws

    container_name: ros2_jammy_simulator
    networks:
      - ros2_internal
    # network_mode: "host"
    # Interactive shell settings
    stdin_open: true
    tty: true
    # Network settings

    # Environment variables
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      # Shell history
      - HISTFILE=/home/ros/.bash_history
      - HISTFILESIZE=10000
      - RCUTILS_COLORIZED_OUTPUT=1
      - GZ_VERSION=harmonic
      - __NV_PRIME_RENDER_OFFLOAD=1

      
    privileged: true  # Fixed spelling and removed duplicate
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ~/.bash_history:/home/ros/.bash_history
      - ./docker_simulator:/home/ros/docker_simulation_ws
      - /dev/input:/dev/input
      - /dev/dri:/dev/dri

      
    # Command to source ROS2 environment and start shell
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        echo 'ROS2 Jazzy environment loaded' &&
        bash
      "


networks:
  ros2_internal:
    driver: bridge
    
