controller_manager:
  ros__parameters:
    update_rate: 100 

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gazebo_joint_controller:
      type: forward_command_controller/ForwardCommandController

    gazebo_velocity_controllers:
      type: forward_command_controller/ForwardCommandController

gazebo_joint_controller:
  ros__parameters:
    joints:
      - CoxisRU_joint
      - FemurRU_joint
      - TibiaRU_joint
      - CoxisLU_joint
      - FemurLU_joint
      - TibiaLU_joint
      - CoxisRD_joint
      - FemurRD_joint
      - TibiaRD_joint
      - CoxisLD_joint
      - FemurLD_joint
      - TibiaLD_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort

gazebo_velocity_controllers:
  ros__parameters:
    joints:
      - RuedaRU_joint
      - RuedaLU_joint
      - RuedaRD_joint
      - RuedaLD_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position
      - effort
