controller_manager:

  # Parametros y definicion de controladores
  ros__parameters:
    update_rate: 100 

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gazebo_joint_controller:
      type: forward_command_controller/ForwardCommandController

    gazebo_velocity_controllers:
      type: forward_command_controller/ForwardCommandController
      
# Controlador FORWARD de articulaciones
gazebo_joint_controller:
  ros__parameters:
    joints:
      - CoxisRU_joint
      - FemurRU_joint
      - TibiaRU_joint
      - BumperRU_joint
      - CoxisLU_joint
      - FemurLU_joint
      - TibiaLU_joint
      - BumperLU_joint
      - CoxisRD_joint
      - FemurRD_joint
      - TibiaRD_joint
      - BumperRD_joint
      - CoxisLD_joint
      - FemurLD_joint
      - TibiaLD_joint
      - BumperLD_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort

# Controlador FORWARD de velocidad
gazebo_velocity_controllers:
  ros__parameters:
    joints:
      - RuedaRU_joint
      - RuedaLU_joint
      - RuedaRD_joint
      - RuedaLD_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position
      - effort

# Controlador FORWARD de cabeza
head_controller:
  ros__parameters:
    joints:
      - Head_z_joint
      - Head_y_joint
    interface_name: position 
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
